### PR TITLE
export server_threads var

### LINKED ISSUE #103: `server_threads` variable not available in `configure_valhalla` script
When running a container using the latest version of the image, the container immediately crashes because the `server_threads` variable initiated in `run.sh` is not available in `configure_valhalla.sh`. This causes `valhalla_build_config` to fail since an empty string is passed as `--mjolnir-concurrency`. 

## Steps to reproduce:   

Just run a container using the docker-compose template, but remove the `server_threads` env var and point it to an osm file.

### PR DESCRIPTION
**Pull request by chrstnbwnkl**
Fixes #103 

First tried to initialize `server_threads` in `helpers.sh` and overwrite it in `run.sh`, but didn't seem to work, so `export` it is I guess? :man_shrugging:

### CODE REVIEW

File: scripts/run.sh [hunk 1]
```diff
@@ -42,6 +42,8 @@ echo ""
 if [[ -z $server_threads ]]; then
   server_threads=$(nproc)
 fi
+export server_threads
```
Comment (nilsnolde) [inline scripts/run.sh:45]: We can export it right away when assigning it

**Review by nilsnolde — COMMENTED** [review]
Weird.. are the tests defining that env var then? I can see it’s only on docker-compose really, which is of course stupid and I wonder why it took so long for someone to notice that😘

**Comment by chrstnbwnkl** [comment]
We test using `server_threads=1`
